// 단어 추가 방법:
// 아래 WORDS 배열에 새 단어를 추가하세요.
// 형식: {word:"단어", clue:"영어 힌트", kr:"한글 힌트(직역)"}
// 주의: 단어는 대문자, 3~7글자 권장

var WORDS = [
{word:"CAT",clue:"Feline pet",kr:"고양잇과 애완동물"},
{word:"DOG",clue:"Man's best friend",kr:"인간의 가장 친한 친구"},
{word:"SUN",clue:"Center of solar system",kr:"태양계의 중심"},
{word:"RUN",clue:"Move quickly on foot",kr:"발로 빠르게 이동"},
{word:"EAT",clue:"Consume food",kr:"음식을 섭취하다"},
{word:"SKY",clue:"Where clouds float",kr:"구름이 떠다니는 곳"},
{word:"RED",clue:"Color of blood",kr:"피의 색깔"},
{word:"CAR",clue:"Four-wheeled vehicle",kr:"네 바퀴 달린 탈것"},
{word:"BOX",clue:"Container with flat sides",kr:"평평한 면을 가진 용기"},
{word:"CUP",clue:"Drinking vessel",kr:"음료를 담는 그릇"},
{word:"MAP",clue:"Geographic diagram",kr:"지리적 도표"},
{word:"PEN",clue:"Writing instrument",kr:"글씨를 쓰는 도구"},
{word:"HAT",clue:"Head covering",kr:"머리에 쓰는 것"},
{word:"BED",clue:"Place to sleep",kr:"잠을 자는 곳"},
{word:"ICE",clue:"Frozen water",kr:"얼어붙은 물"},
{word:"OWL",clue:"Nocturnal bird",kr:"야행성 조류"},
{word:"ANT",clue:"Small insect",kr:"작은 곤충"},
{word:"BAT",clue:"Flying mammal",kr:"날아다니는 포유류"},
{word:"FOX",clue:"Cunning animal",kr:"교활한 동물"},
{word:"KEY",clue:"Lock opener",kr:"자물쇠를 여는 것"},
{word:"NET",clue:"Fishing tool",kr:"물고기 잡는 도구"},
{word:"PIE",clue:"Baked dessert",kr:"구운 디저트"},
{word:"TEA",clue:"Hot beverage",kr:"뜨거운 음료"},
{word:"WEB",clue:"Spider's creation",kr:"거미가 만드는 것"},
{word:"ZOO",clue:"Animal park",kr:"동물들이 사는 공원"},
{word:"ART",clue:"Creative expression",kr:"창의적 표현"},
{word:"EGG",clue:"Breakfast food",kr:"아침 식사 음식"},
{word:"GYM",clue:"Exercise place",kr:"운동하는 장소"},
{word:"INK",clue:"Pen fluid",kr:"펜에 들어가는 액체"},
{word:"JOB",clue:"Employment",kr:"고용 상태"},
{word:"JAM",clue:"Fruit spread",kr:"과일 스프레드"},
{word:"JAR",clue:"Glass container",kr:"유리 용기"},
{word:"JOY",clue:"Happiness",kr:"행복"},
{word:"LAW",clue:"Legal rule",kr:"법적 규칙"},
{word:"LEG",clue:"Walking limb",kr:"걷는 팔다리"},
{word:"LOG",clue:"Wood piece",kr:"나무 조각"},
{word:"MAN",clue:"Adult male",kr:"성인 남성"},
{word:"MUD",clue:"Wet earth",kr:"젖은 흙"},
{word:"NUT",clue:"Tree seed",kr:"나무 씨앗"},
{word:"OAK",clue:"Strong tree",kr:"튼튼한 나무"},
{word:"OIL",clue:"Liquid fat",kr:"액체 지방"},
{word:"OLD",clue:"Not young",kr:"젊지 않은"},
{word:"PAN",clue:"Cooking vessel",kr:"요리 용기"},
{word:"PAW",clue:"Animal foot",kr:"동물 발"},
{word:"PIG",clue:"Farm animal",kr:"농장 동물"},
{word:"POT",clue:"Cooking container",kr:"요리 용기"},
{word:"RAT",clue:"Rodent",kr:"설치류"},
{word:"ROW",clue:"Line of seats",kr:"좌석 줄"},
{word:"SAD",clue:"Unhappy",kr:"슬픈"},
{word:"SAW",clue:"Cutting tool",kr:"자르는 도구"},
{word:"SEA",clue:"Ocean",kr:"바다"},
{word:"SIT",clue:"Be seated",kr:"앉다"},
{word:"SIX",clue:"Number after five",kr:"5 다음 숫자"},
{word:"TEN",clue:"Number after nine",kr:"9 다음 숫자"},
{word:"TIE",clue:"Neck accessory",kr:"목 액세서리"},
{word:"TOE",clue:"Foot digit",kr:"발가락"},
{word:"TOP",clue:"Highest point",kr:"가장 높은 점"},
{word:"TOY",clue:"Plaything",kr:"장난감"},
{word:"TWO",clue:"Number after one",kr:"1 다음 숫자"},
{word:"VAN",clue:"Large vehicle",kr:"큰 차량"},
{word:"WAR",clue:"Armed conflict",kr:"무력 충돌"},
{word:"WAX",clue:"Candle material",kr:"초 재료"},
{word:"WAY",clue:"Path",kr:"길"},
{word:"WET",clue:"Not dry",kr:"마르지 않은"},
{word:"WIN",clue:"Be victorious",kr:"승리하다"},
{word:"YES",clue:"Affirmative",kr:"긍정"},
{word:"ZIP",clue:"Move fast",kr:"빠르게 이동"},
{word:"BOOK",clue:"Reading material",kr:"읽을거리"},
{word:"FISH",clue:"Aquatic animal",kr:"수중 동물"},
{word:"MOON",clue:"Earth's satellite",kr:"지구의 위성"},
{word:"STAR",clue:"Celestial body",kr:"천체"},
{word:"TREE",clue:"Tall plant",kr:"키가 큰 식물"},
{word:"BIRD",clue:"Feathered creature",kr:"깃털 달린 생물"},
{word:"RAIN",clue:"Water from clouds",kr:"구름에서 내리는 물"},
{word:"SNOW",clue:"Winter precipitation",kr:"겨울 강수"},
{word:"WIND",clue:"Moving air",kr:"움직이는 공기"},
{word:"FIRE",clue:"Burning flames",kr:"타오르는 불꽃"},
{word:"GOLD",clue:"Precious metal",kr:"귀중한 금속"},
{word:"BLUE",clue:"Color of the sky",kr:"하늘의 색깔"},
{word:"FROG",clue:"Amphibian that hops",kr:"뛰어다니는 양서류"},
{word:"KING",clue:"Royal ruler",kr:"왕족 통치자"},
{word:"SHIP",clue:"Ocean vessel",kr:"바다를 다니는 배"},
{word:"LOVE",clue:"Deep affection",kr:"깊은 애정"},
{word:"HOPE",clue:"Optimistic feeling",kr:"낙관적인 감정"},
{word:"WAVE",clue:"Ocean movement",kr:"바다의 움직임"},
{word:"DESK",clue:"Work surface",kr:"작업하는 표면"},
{word:"LAMP",clue:"Light source",kr:"빛을 내는 기구"},
{word:"DOOR",clue:"Room entrance",kr:"방의 입구"},
{word:"WALL",clue:"Room divider",kr:"방을 나누는 것"},
{word:"CAKE",clue:"Birthday dessert",kr:"생일 디저트"},
{word:"MILK",clue:"Dairy drink",kr:"유제품 음료"},
{word:"RICE",clue:"Asian staple grain",kr:"아시아 주식 곡물"},
{word:"SALT",clue:"Table seasoning",kr:"식탁 양념"},
{word:"BEAR",clue:"Large furry mammal",kr:"크고 털이 많은 포유류"},
{word:"DEER",clue:"Forest animal",kr:"숲 동물"},
{word:"WOLF",clue:"Wild canine",kr:"야생 개과 동물"},
{word:"LION",clue:"King of the jungle",kr:"정글의 왕"},
{word:"DUCK",clue:"Quacking bird",kr:"꽥꽥 우는 새"},
{word:"COIN",clue:"Metal money",kr:"금속으로 된 화폐"},
{word:"GAME",clue:"Fun activity",kr:"재미있는 활동"},
{word:"BALL",clue:"Round toy",kr:"둥근 장난감"},
{word:"BOAT",clue:"Small watercraft",kr:"작은 수상 운송수단"},
{word:"CITY",clue:"Urban area",kr:"도시 지역"},
{word:"COAT",clue:"Outer garment",kr:"겉에 입는 옷"},
{word:"FARM",clue:"Agricultural land",kr:"농업용 토지"},
{word:"FLAG",clue:"National symbol",kr:"국가 상징물"},
{word:"FORK",clue:"Eating utensil",kr:"식사 도구"},
{word:"GIFT",clue:"Present",kr:"선물"},
{word:"HAIR",clue:"Head strands",kr:"머리에 나는 가닥"},
{word:"HAND",clue:"Body part with fingers",kr:"손가락이 있는 신체 부위"},
{word:"HERO",clue:"Brave person",kr:"용감한 사람"},
{word:"HILL",clue:"Small mountain",kr:"작은 산"},
{word:"HOME",clue:"Where you live",kr:"사는 곳"},
{word:"HOUR",clue:"60 minutes",kr:"60분"},
{word:"IDEA",clue:"Thought concept",kr:"생각의 개념"},
{word:"IRON",clue:"Strong metal",kr:"강한 금속"},
{word:"JOKE",clue:"Something funny",kr:"웃긴 것"},
{word:"JUMP",clue:"Leap in the air",kr:"공중으로 뛰기"},
{word:"LAKE",clue:"Body of fresh water",kr:"담수 수역"},
{word:"LEAF",clue:"Tree part",kr:"나무의 일부"},
{word:"LIFE",clue:"Existence",kr:"존재함"},
{word:"LINE",clue:"Straight mark",kr:"곧은 표시"},
{word:"LOCK",clue:"Security device",kr:"보안 장치"},
{word:"MEAL",clue:"Food serving",kr:"음식 제공"},
{word:"MEAT",clue:"Animal flesh food",kr:"동물의 살"},
{word:"NAME",clue:"What you're called",kr:"불리는 것"},
{word:"NECK",clue:"Body part below head",kr:"머리 아래 신체 부위"},
{word:"NEWS",clue:"Current events",kr:"현재 사건들"},
{word:"NOSE",clue:"Smelling organ",kr:"냄새 맡는 기관"},
{word:"PAGE",clue:"Book sheet",kr:"책의 장"},
{word:"PARK",clue:"Green public space",kr:"녹색 공공 공간"},
{word:"PATH",clue:"Walking trail",kr:"걷는 길"},
{word:"ROCK",clue:"Stone",kr:"돌"},
{word:"ROAD",clue:"Driving surface",kr:"차가 다니는 곳"},
{word:"ROOM",clue:"Indoor space",kr:"실내 공간"},
{word:"ROOF",clue:"Building top",kr:"건물 꼭대기"},
{word:"ROSE",clue:"Romantic flower",kr:"로맨틱한 꽃"},
{word:"SAND",clue:"Beach material",kr:"해변의 재료"},
{word:"SEED",clue:"Plant starter",kr:"식물의 시작"},
{word:"SHOP",clue:"Retail store",kr:"소매점"},
{word:"SONG",clue:"Musical piece",kr:"음악 작품"},
{word:"STEP",clue:"Walking motion",kr:"걷는 동작"},
{word:"SWIM",clue:"Water movement",kr:"물속 이동"},
{word:"TAIL",clue:"Animal rear",kr:"동물 뒤쪽 부속물"},
{word:"TEAM",clue:"Group working together",kr:"함께 일하는 집단"},
{word:"TEST",clue:"Examination",kr:"시험"},
{word:"TOOL",clue:"Work instrument",kr:"작업 기구"},
{word:"TOWN",clue:"Small city",kr:"작은 도시"},
{word:"TRIP",clue:"Journey",kr:"여정"},
{word:"WALK",clue:"On foot movement",kr:"도보 이동"},
{word:"WEEK",clue:"Seven days",kr:"7일"},
{word:"WINE",clue:"Grape beverage",kr:"포도 음료"},
{word:"WOOD",clue:"Tree material",kr:"나무 재료"},
{word:"WORD",clue:"Language unit",kr:"언어 단위"},
{word:"WORK",clue:"Job activity",kr:"직업 활동"},
{word:"YEAR",clue:"365 days",kr:"365일"},
{word:"ARMY",clue:"Military force",kr:"군대"},
{word:"BACK",clue:"Rear side",kr:"뒷면"},
{word:"BAND",clue:"Musical group",kr:"음악 그룹"},
{word:"BANK",clue:"Financial institution",kr:"금융 기관"},
{word:"BELL",clue:"Ringing device",kr:"울리는 장치"},
{word:"BELT",clue:"Waist band",kr:"허리띠"},
{word:"BIKE",clue:"Two-wheeled vehicle",kr:"두 바퀴 탈것"},
{word:"BONE",clue:"Skeleton part",kr:"골격 일부"},
{word:"BOWL",clue:"Deep dish",kr:"깊은 접시"},
{word:"CAFE",clue:"Coffee shop",kr:"커피숍"},
{word:"CAGE",clue:"Animal enclosure",kr:"동물 우리"},
{word:"CALL",clue:"Phone action",kr:"전화 행위"},
{word:"CALM",clue:"Peaceful",kr:"평화로운"},
{word:"CAMP",clue:"Outdoor stay",kr:"야외 숙박"},
{word:"CARD",clue:"Paper rectangle",kr:"종이 직사각형"},
{word:"CARE",clue:"Concern",kr:"관심"},
{word:"CASH",clue:"Paper money",kr:"지폐"},
{word:"CAVE",clue:"Rock hollow",kr:"바위 동굴"},
{word:"CHEF",clue:"Cook",kr:"요리사"},
{word:"CHIP",clue:"Small piece",kr:"작은 조각"},
{word:"CLAY",clue:"Pottery material",kr:"도자기 재료"},
{word:"CLUB",clue:"Social group",kr:"사교 모임"},
{word:"CLUE",clue:"Hint",kr:"힌트"},
{word:"COAL",clue:"Black fuel",kr:"검은 연료"},
{word:"COLD",clue:"Low temperature",kr:"낮은 온도"},
{word:"COOL",clue:"Slightly cold",kr:"약간 차가운"},
{word:"COPY",clue:"Duplicate",kr:"복제"},
{word:"CORN",clue:"Yellow grain",kr:"노란 곡물"},
{word:"COST",clue:"Price",kr:"가격"},
{word:"CRAB",clue:"Sea creature",kr:"바다 생물"},
{word:"CREW",clue:"Work team",kr:"작업팀"},
{word:"CROP",clue:"Farm produce",kr:"농산물"},
{word:"CROW",clue:"Black bird",kr:"검은 새"},
{word:"CURE",clue:"Remedy",kr:"치료"},
{word:"DARK",clue:"Without light",kr:"빛이 없는"},
{word:"DATA",clue:"Information",kr:"정보"},
{word:"DATE",clue:"Calendar day",kr:"달력의 날"},
{word:"DAWN",clue:"Early morning",kr:"이른 아침"},
{word:"DEAL",clue:"Agreement",kr:"합의"},
{word:"DEAR",clue:"Beloved",kr:"사랑하는"},
{word:"DEBT",clue:"Money owed",kr:"빚"},
{word:"DECK",clue:"Ship floor",kr:"배의 갑판"},
{word:"DEEP",clue:"Far down",kr:"깊은"},
{word:"DICE",clue:"Game cubes",kr:"게임 주사위"},
{word:"DIET",clue:"Eating plan",kr:"식이요법"},
{word:"DIRT",clue:"Soil",kr:"흙"},
{word:"DISK",clue:"Round plate",kr:"원형 판"},
{word:"DIVE",clue:"Plunge",kr:"뛰어들다"},
{word:"DOCK",clue:"Boat pier",kr:"선착장"},
{word:"DOME",clue:"Rounded roof",kr:"둥근 지붕"},
{word:"DOWN",clue:"Lower direction",kr:"아래 방향"},
{word:"DRAG",clue:"Pull along",kr:"끌다"},
{word:"DRAW",clue:"Sketch",kr:"스케치하다"},
{word:"DROP",clue:"Let fall",kr:"떨어뜨리다"},
{word:"DRUM",clue:"Percussion instrument",kr:"타악기"},
{word:"DUST",clue:"Fine particles",kr:"미세한 입자"},
{word:"DUTY",clue:"Responsibility",kr:"책임"},
{word:"EACH",clue:"Every one",kr:"각각"},
{word:"EARN",clue:"Make money",kr:"돈을 벌다"},
{word:"EASE",clue:"Comfort",kr:"편안함"},
{word:"EAST",clue:"Sunrise direction",kr:"해 뜨는 방향"},
{word:"EASY",clue:"Not difficult",kr:"어렵지 않은"},
{word:"EDGE",clue:"Border",kr:"가장자리"},
{word:"EDIT",clue:"Revise",kr:"수정하다"},
{word:"EVEN",clue:"Level",kr:"평평한"},
{word:"EVIL",clue:"Wicked",kr:"사악한"},
{word:"EXAM",clue:"Test",kr:"시험"},
{word:"EXIT",clue:"Way out",kr:"출구"},
{word:"FACE",clue:"Front of head",kr:"머리 앞면"},
{word:"FACT",clue:"Truth",kr:"사실"},
{word:"FADE",clue:"Lose color",kr:"색이 바래다"},
{word:"FAIL",clue:"Not succeed",kr:"실패하다"},
{word:"FAIR",clue:"Just",kr:"공정한"},
{word:"FAKE",clue:"Not real",kr:"가짜의"},
{word:"FALL",clue:"Drop down",kr:"떨어지다"},
{word:"FAME",clue:"Renown",kr:"명성"},
{word:"FAST",clue:"Quick",kr:"빠른"},
{word:"FATE",clue:"Destiny",kr:"운명"},
{word:"FEAR",clue:"Fright",kr:"두려움"},
{word:"FEED",clue:"Give food",kr:"먹이를 주다"},
{word:"FEEL",clue:"Sense",kr:"느끼다"},
{word:"FILE",clue:"Document",kr:"문서"},
{word:"FILL",clue:"Make full",kr:"채우다"},
{word:"FILM",clue:"Movie",kr:"영화"},
{word:"FIND",clue:"Discover",kr:"발견하다"},
{word:"FINE",clue:"Good quality",kr:"좋은 품질"},
{word:"FIRM",clue:"Company",kr:"회사"},
{word:"FIVE",clue:"Number after four",kr:"4 다음 숫자"},
{word:"FLAT",clue:"Level surface",kr:"평평한 표면"},
{word:"FLOW",clue:"Move smoothly",kr:"부드럽게 흐르다"},
{word:"FOAM",clue:"Bubbles",kr:"거품"},
{word:"FOLD",clue:"Bend over",kr:"접다"},
{word:"FOLK",clue:"People",kr:"사람들"},
{word:"FOOD",clue:"Nourishment",kr:"음식"},
{word:"FOOT",clue:"Body part",kr:"발"},
{word:"FORM",clue:"Shape",kr:"모양"},
{word:"FOUR",clue:"Number after three",kr:"3 다음 숫자"},
{word:"FREE",clue:"No cost",kr:"무료의"},
{word:"FUEL",clue:"Energy source",kr:"에너지원"},
{word:"FULL",clue:"Completely filled",kr:"완전히 채워진"},
{word:"FUND",clue:"Money reserve",kr:"자금"},
{word:"GAIN",clue:"Acquire",kr:"얻다"},
{word:"GATE",clue:"Entrance barrier",kr:"입구 문"},
{word:"GEAR",clue:"Equipment",kr:"장비"},
{word:"GIRL",clue:"Young female",kr:"어린 여성"},
{word:"GIVE",clue:"Provide",kr:"주다"},
{word:"GLAD",clue:"Happy",kr:"기쁜"},
{word:"GLOW",clue:"Shine softly",kr:"부드럽게 빛나다"},
{word:"GLUE",clue:"Adhesive",kr:"접착제"},
{word:"GOAL",clue:"Objective",kr:"목표"},
{word:"GOAT",clue:"Farm animal",kr:"농장 동물"},
{word:"GOOD",clue:"Positive quality",kr:"좋은 품질"},
{word:"GRAB",clue:"Seize",kr:"잡다"},
{word:"GRAY",clue:"Neutral color",kr:"중립 색상"},
{word:"GRID",clue:"Network pattern",kr:"격자 패턴"},
{word:"GRIN",clue:"Wide smile",kr:"활짝 웃음"},
{word:"GRIP",clue:"Hold tightly",kr:"꽉 잡다"},
{word:"GROW",clue:"Increase",kr:"자라다"},
{word:"GULF",clue:"Large bay",kr:"큰 만"},
{word:"GUST",clue:"Wind burst",kr:"돌풍"},
{word:"HAIL",clue:"Ice pellets",kr:"우박"},
{word:"HALF",clue:"50 percent",kr:"50퍼센트"},
{word:"HALL",clue:"Corridor",kr:"복도"},
{word:"HALT",clue:"Stop",kr:"멈추다"},
{word:"HANG",clue:"Suspend",kr:"매달다"},
{word:"HARD",clue:"Not soft",kr:"단단한"},
{word:"HARM",clue:"Damage",kr:"피해"},
{word:"HATE",clue:"Strong dislike",kr:"강한 싫어함"},
{word:"HAVE",clue:"Possess",kr:"가지다"},
{word:"HAWK",clue:"Bird of prey",kr:"맹금류"},
{word:"HEAD",clue:"Body top",kr:"머리"},
{word:"HEAL",clue:"Cure",kr:"치유하다"},
{word:"HEAP",clue:"Pile",kr:"더미"},
{word:"HEAR",clue:"Listen",kr:"듣다"},
{word:"HEAT",clue:"Warmth",kr:"열"},
{word:"HELP",clue:"Assist",kr:"돕다"},
{word:"HERB",clue:"Cooking plant",kr:"요리용 허브"},
{word:"HERD",clue:"Animal group",kr:"동물 떼"},
{word:"HERE",clue:"This place",kr:"이곳"},
{word:"HIDE",clue:"Conceal",kr:"숨기다"},
{word:"HIGH",clue:"Tall",kr:"높은"},
{word:"HIKE",clue:"Long walk",kr:"긴 도보 여행"},
{word:"HINT",clue:"Clue",kr:"힌트"},
{word:"HIRE",clue:"Employ",kr:"고용하다"},
{word:"HOLD",clue:"Grasp",kr:"잡다"},
{word:"HOLE",clue:"Opening",kr:"구멍"},
{word:"HOLY",clue:"Sacred",kr:"신성한"},
{word:"HOOK",clue:"Curved device",kr:"갈고리"},
{word:"HORN",clue:"Animal protrusion",kr:"동물 뿔"},
{word:"HOST",clue:"Event organizer",kr:"행사 주최자"},
{word:"HUGE",clue:"Very large",kr:"매우 큰"},
{word:"HUNT",clue:"Chase prey",kr:"사냥하다"},
{word:"HURT",clue:"Cause pain",kr:"아프게 하다"},
{word:"ICON",clue:"Symbol",kr:"상징"},
{word:"INCH",clue:"Small length",kr:"작은 길이"},
{word:"INTO",clue:"Inside",kr:"안으로"},
{word:"ITEM",clue:"Object",kr:"물건"},
{word:"JAIL",clue:"Prison",kr:"감옥"},
{word:"JAZZ",clue:"Music genre",kr:"음악 장르"},
{word:"JEAN",clue:"Denim pants",kr:"청바지"},
{word:"JOIN",clue:"Connect",kr:"연결하다"},
{word:"JURY",clue:"Trial group",kr:"배심원"},
{word:"JUST",clue:"Fair",kr:"공정한"},
{word:"KEEN",clue:"Eager",kr:"열망하는"},
{word:"KEEP",clue:"Retain",kr:"유지하다"},
{word:"KICK",clue:"Foot strike",kr:"발로 차다"},
{word:"KIND",clue:"Nice type",kr:"친절한"},
{word:"KITE",clue:"Flying toy",kr:"연"},
{word:"KNEE",clue:"Leg joint",kr:"무릎"},
{word:"KNOT",clue:"Tied rope",kr:"매듭"},
{word:"KNOW",clue:"Understand",kr:"알다"},
{word:"LACE",clue:"Shoe string",kr:"신발끈"},
{word:"LACK",clue:"Be without",kr:"부족하다"},
{word:"LAND",clue:"Ground",kr:"땅"},
{word:"LANE",clue:"Narrow road",kr:"좁은 길"},
{word:"LAST",clue:"Final",kr:"마지막"},
{word:"LATE",clue:"Not on time",kr:"늦은"},
{word:"LAWN",clue:"Grass yard",kr:"잔디밭"},
{word:"LEAD",clue:"Guide",kr:"이끌다"},
{word:"LEAK",clue:"Drip out",kr:"새다"},
{word:"LEAN",clue:"Tilt",kr:"기울다"},
{word:"LEAP",clue:"Jump",kr:"뛰다"},
{word:"LEFT",clue:"Not right",kr:"왼쪽"},
{word:"LEND",clue:"Loan",kr:"빌려주다"},
{word:"LENS",clue:"Camera part",kr:"카메라 부품"},
{word:"LESS",clue:"Smaller amount",kr:"더 작은 양"},
{word:"LIFT",clue:"Raise up",kr:"들어 올리다"},
{word:"LIMB",clue:"Body appendage",kr:"팔다리"},
{word:"LINK",clue:"Connection",kr:"연결"},
{word:"LIST",clue:"Items written",kr:"목록"},
{word:"LIVE",clue:"Exist",kr:"살다"},
{word:"LOAD",clue:"Cargo",kr:"화물"},
{word:"LOAN",clue:"Borrowed money",kr:"빌린 돈"},
{word:"LONG",clue:"Not short",kr:"긴"},
{word:"LOOK",clue:"See",kr:"보다"},
{word:"LOOP",clue:"Circle shape",kr:"고리 모양"},
{word:"LOSE",clue:"Misplace",kr:"잃다"},
{word:"LOSS",clue:"Defeat",kr:"손실"},
{word:"LOST",clue:"Not found",kr:"길 잃은"},
{word:"LOUD",clue:"High volume",kr:"시끄러운"},
{word:"LUCK",clue:"Fortune",kr:"행운"},
{word:"LUNG",clue:"Breathing organ",kr:"호흡 기관"},
{word:"MAIL",clue:"Post",kr:"우편"},
{word:"MAIN",clue:"Primary",kr:"주요한"},
{word:"MAKE",clue:"Create",kr:"만들다"},
{word:"MALE",clue:"Man",kr:"남성"},
{word:"MALL",clue:"Shopping center",kr:"쇼핑센터"},
{word:"MANY",clue:"A lot",kr:"많은"},
{word:"MARK",clue:"Sign",kr:"표시"},
{word:"MASK",clue:"Face covering",kr:"마스크"},
{word:"MATH",clue:"Number subject",kr:"수학"},
{word:"MAZE",clue:"Labyrinth",kr:"미로"},
{word:"MEET",clue:"Encounter",kr:"만나다"},
{word:"MELT",clue:"Become liquid",kr:"녹다"},
{word:"MENU",clue:"Food list",kr:"메뉴"},
{word:"MESS",clue:"Disorder",kr:"엉망"},
{word:"MILD",clue:"Not strong",kr:"순한"},
{word:"MILE",clue:"Distance unit",kr:"거리 단위"},
{word:"MIND",clue:"Brain",kr:"마음"},
{word:"MINE",clue:"Belonging to me",kr:"나의 것"},
{word:"MINT",clue:"Herb flavor",kr:"민트"},
{word:"MISS",clue:"Fail to hit",kr:"놓치다"},
{word:"MODE",clue:"Method",kr:"방식"},
{word:"MOOD",clue:"Emotional state",kr:"기분"},
{word:"MORE",clue:"Additional",kr:"더 많은"},
{word:"MOST",clue:"Greatest amount",kr:"가장 많은"},
{word:"MOTH",clue:"Night insect",kr:"나방"},
{word:"MOVE",clue:"Change position",kr:"움직이다"},
{word:"MUCH",clue:"A lot",kr:"많이"},
{word:"MUST",clue:"Have to",kr:"해야 한다"},
{word:"MYTH",clue:"Legend",kr:"신화"},
{word:"NAIL",clue:"Finger cover",kr:"손톱"},
{word:"NEAR",clue:"Close by",kr:"가까운"},
{word:"NEAT",clue:"Tidy",kr:"깔끔한"},
{word:"NEED",clue:"Require",kr:"필요하다"},
{word:"NEST",clue:"Bird home",kr:"새 둥지"},
{word:"NEXT",clue:"Following",kr:"다음의"},
{word:"NICE",clue:"Pleasant",kr:"좋은"},
{word:"NINE",clue:"Number after eight",kr:"8 다음 숫자"},
{word:"NONE",clue:"Zero",kr:"없음"},
{word:"NOON",clue:"Midday",kr:"정오"},
{word:"NORM",clue:"Standard",kr:"표준"},
{word:"NOTE",clue:"Written message",kr:"메모"},
{word:"OKAY",clue:"Alright",kr:"괜찮은"},
{word:"ONCE",clue:"One time",kr:"한 번"},
{word:"ONLY",clue:"Sole",kr:"유일한"},
{word:"OPEN",clue:"Not closed",kr:"열린"},
{word:"OVEN",clue:"Cooking device",kr:"오븐"},
{word:"OVER",clue:"Above",kr:"위에"},
{word:"PACE",clue:"Walking speed",kr:"걷는 속도"},
{word:"PACK",clue:"Bundle",kr:"꾸러미"},
{word:"PAIN",clue:"Hurt feeling",kr:"고통"},
{word:"PAIR",clue:"Two items",kr:"한 쌍"},
{word:"PALE",clue:"Light colored",kr:"창백한"},
{word:"PALM",clue:"Hand center",kr:"손바닥"},
{word:"PART",clue:"Piece",kr:"부분"},
{word:"PASS",clue:"Go by",kr:"지나가다"},
{word:"PAST",clue:"Before now",kr:"과거"},
{word:"PEAK",clue:"Mountain top",kr:"산꼭대기"},
{word:"PEAR",clue:"Fruit",kr:"배"},
{word:"PICK",clue:"Choose",kr:"선택하다"},
{word:"PILE",clue:"Stack",kr:"더미"},
{word:"PILL",clue:"Medicine tablet",kr:"알약"},
{word:"PINE",clue:"Evergreen tree",kr:"소나무"},
{word:"PINK",clue:"Light red",kr:"분홍색"},
{word:"PIPE",clue:"Tube",kr:"파이프"},
{word:"PLAN",clue:"Strategy",kr:"계획"},
{word:"PLAY",clue:"Have fun",kr:"놀다"},
{word:"PLOT",clue:"Story plan",kr:"줄거리"},
{word:"PLUG",clue:"Stopper",kr:"플러그"},
{word:"PLUS",clue:"Addition sign",kr:"더하기"},
{word:"POEM",clue:"Verse writing",kr:"시"},
{word:"POET",clue:"Verse writer",kr:"시인"},
{word:"POKE",clue:"Prod",kr:"찌르다"},
{word:"POLE",clue:"Long stick",kr:"기둥"},
{word:"POLL",clue:"Survey",kr:"설문조사"},
{word:"POND",clue:"Small lake",kr:"연못"},
{word:"POOL",clue:"Swimming place",kr:"수영장"},
{word:"POOR",clue:"Not rich",kr:"가난한"},
{word:"PORK",clue:"Pig meat",kr:"돼지고기"},
{word:"PORT",clue:"Harbor",kr:"항구"},
{word:"POSE",clue:"Position",kr:"포즈"},
{word:"POST",clue:"Mail",kr:"우편물"},
{word:"POUR",clue:"Flow out",kr:"붓다"},
{word:"PRAY",clue:"Worship",kr:"기도하다"},
{word:"PULL",clue:"Draw toward",kr:"당기다"},
{word:"PUMP",clue:"Fluid mover",kr:"펌프"},
{word:"PURE",clue:"Clean",kr:"순수한"},
{word:"PUSH",clue:"Shove",kr:"밀다"},
{word:"QUIT",clue:"Stop doing",kr:"그만두다"},
{word:"QUIZ",clue:"Short test",kr:"퀴즈"},
{word:"RACE",clue:"Competition",kr:"경주"},
{word:"RACK",clue:"Storage frame",kr:"선반"},
{word:"RAGE",clue:"Extreme anger",kr:"격노"},
{word:"RAIL",clue:"Track bar",kr:"레일"},
{word:"RANK",clue:"Position level",kr:"순위"},
{word:"RARE",clue:"Uncommon",kr:"드문"},
{word:"RATE",clue:"Speed",kr:"비율"},
{word:"READ",clue:"Look at text",kr:"읽다"},
{word:"REAL",clue:"Genuine",kr:"진짜의"},
{word:"REAR",clue:"Back part",kr:"뒤쪽"},
{word:"RENT",clue:"Pay for use",kr:"임대료"},
{word:"REST",clue:"Relax",kr:"휴식"},
{word:"RICH",clue:"Wealthy",kr:"부유한"},
{word:"RIDE",clue:"Travel on",kr:"타다"},
{word:"RING",clue:"Circular band",kr:"반지"},
{word:"RISK",clue:"Danger",kr:"위험"},
{word:"RULE",clue:"Regulation",kr:"규칙"},
{word:"RUSH",clue:"Hurry",kr:"서두르다"},
{word:"SAFE",clue:"Secure",kr:"안전한"},
{word:"SAID",clue:"Past of say",kr:"say의 과거형"},
{word:"SAIL",clue:"Boat cloth",kr:"돛"},
{word:"SALE",clue:"Discount event",kr:"할인 판매"},
{word:"SAME",clue:"Identical",kr:"같은"},
{word:"SAVE",clue:"Rescue",kr:"구하다"},
{word:"SEAL",clue:"Close tight",kr:"봉인하다"},
{word:"SEAT",clue:"Chair",kr:"좌석"},
{word:"SEEK",clue:"Search for",kr:"찾다"},
{word:"SEEM",clue:"Appear",kr:"보이다"},
{word:"SELF",clue:"Own person",kr:"자아"},
{word:"SELL",clue:"Trade for money",kr:"팔다"},
{word:"SEND",clue:"Dispatch",kr:"보내다"},
{word:"SHIP",clue:"Large boat",kr:"배"},
{word:"SHOW",clue:"Display",kr:"보여주다"},
{word:"SHUT",clue:"Close",kr:"닫다"},
{word:"SICK",clue:"Ill",kr:"아픈"},
{word:"SIDE",clue:"Edge",kr:"옆면"},
{word:"SIGN",clue:"Symbol",kr:"표지판"},
{word:"SILK",clue:"Smooth fabric",kr:"실크"},
{word:"SING",clue:"Make music",kr:"노래하다"},
{word:"SINK",clue:"Go down",kr:"가라앉다"},
{word:"SIZE",clue:"Dimension",kr:"크기"},
{word:"SKIN",clue:"Body covering",kr:"피부"},
{word:"SKIP",clue:"Jump over",kr:"건너뛰다"},
{word:"SLOW",clue:"Not fast",kr:"느린"},
{word:"SNAP",clue:"Break suddenly",kr:"딱 부러지다"},
{word:"SOAK",clue:"Make wet",kr:"적시다"},
{word:"SOAP",clue:"Cleaning agent",kr:"비누"},
{word:"SOAR",clue:"Fly high",kr:"높이 날다"},
{word:"SOCK",clue:"Foot covering",kr:"양말"},
{word:"SODA",clue:"Fizzy drink",kr:"탄산음료"},
{word:"SOFA",clue:"Couch",kr:"소파"},
{word:"SOFT",clue:"Not hard",kr:"부드러운"},
{word:"SOIL",clue:"Earth",kr:"흙"},
{word:"SOLE",clue:"Only one",kr:"유일한"},
{word:"SOME",clue:"A few",kr:"몇몇"},
{word:"SOON",clue:"Shortly",kr:"곧"},
{word:"SORE",clue:"Painful",kr:"아픈"},
{word:"SORT",clue:"Type",kr:"종류"},
{word:"SOUL",clue:"Spirit",kr:"영혼"},
{word:"SOUP",clue:"Liquid food",kr:"수프"},
{word:"SOUR",clue:"Acidic taste",kr:"신맛"},
{word:"SPIN",clue:"Turn around",kr:"회전하다"},
{word:"SPOT",clue:"Location",kr:"장소"},
{word:"STAY",clue:"Remain",kr:"머무르다"},
{word:"STEM",clue:"Plant stalk",kr:"줄기"},
{word:"STOP",clue:"Cease",kr:"멈추다"},
{word:"SUCH",clue:"Of that kind",kr:"그러한"},
{word:"SUIT",clue:"Formal outfit",kr:"정장"},
{word:"SURE",clue:"Certain",kr:"확실한"},
{word:"SURF",clue:"Ride waves",kr:"서핑하다"},
{word:"TALK",clue:"Speak",kr:"말하다"},
{word:"TALL",clue:"High",kr:"키가 큰"},
{word:"TANK",clue:"Container",kr:"탱크"},
{word:"TAPE",clue:"Adhesive strip",kr:"테이프"},
{word:"TASK",clue:"Job to do",kr:"할 일"},
{word:"TAXI",clue:"Hired car",kr:"택시"},
{word:"TELL",clue:"Inform",kr:"말하다"},
{word:"TENT",clue:"Camping shelter",kr:"텐트"},
{word:"TERM",clue:"Period",kr:"기간"},
{word:"TEXT",clue:"Written words",kr:"문자"},
{word:"THAN",clue:"Comparison word",kr:"~보다"},
{word:"THAT",clue:"Which one",kr:"그것"},
{word:"THEM",clue:"Those people",kr:"그들을"},
{word:"THEN",clue:"Next",kr:"그때"},
{word:"THEY",clue:"Those people",kr:"그들"},
{word:"THIN",clue:"Not thick",kr:"얇은"},
{word:"THIS",clue:"Current one",kr:"이것"},
{word:"THUS",clue:"Therefore",kr:"그러므로"},
{word:"TICK",clue:"Clock sound",kr:"똑딱"},
{word:"TIDE",clue:"Ocean movement",kr:"조수"},
{word:"TIDY",clue:"Neat",kr:"정돈된"},
{word:"TIED",clue:"Fastened",kr:"묶인"},
{word:"TIER",clue:"Level",kr:"층"},
{word:"TILE",clue:"Floor piece",kr:"타일"},
{word:"TILL",clue:"Until",kr:"~까지"},
{word:"TILT",clue:"Slant",kr:"기울이다"},
{word:"TIME",clue:"Hours and minutes",kr:"시간"},
{word:"TINY",clue:"Very small",kr:"아주 작은"},
{word:"TIRE",clue:"Wheel rubber",kr:"타이어"},
{word:"TOAD",clue:"Frog cousin",kr:"두꺼비"},
{word:"TOLL",clue:"Road fee",kr:"통행료"},
{word:"TOMB",clue:"Burial place",kr:"무덤"},
{word:"TONE",clue:"Sound quality",kr:"음색"},
{word:"TOOK",clue:"Past of take",kr:"take의 과거형"},
{word:"TOPS",clue:"Upper parts",kr:"꼭대기들"},
{word:"TORN",clue:"Ripped",kr:"찢어진"},
{word:"TOSS",clue:"Throw",kr:"던지다"},
{word:"TOUR",clue:"Journey",kr:"여행"},
{word:"TRAP",clue:"Snare",kr:"덫"},
{word:"TRAY",clue:"Serving plate",kr:"쟁반"},
{word:"TRIM",clue:"Cut edges",kr:"다듬다"},
{word:"TRUE",clue:"Factual",kr:"사실인"},
{word:"TUBE",clue:"Hollow cylinder",kr:"튜브"},
{word:"TUNA",clue:"Fish type",kr:"참치"},
{word:"TUNE",clue:"Melody",kr:"멜로디"},
{word:"TURN",clue:"Rotate",kr:"돌리다"},
{word:"TWIN",clue:"Identical sibling",kr:"쌍둥이"},
{word:"TYPE",clue:"Kind",kr:"종류"},
{word:"UGLY",clue:"Not pretty",kr:"못생긴"},
{word:"UNDO",clue:"Reverse",kr:"취소하다"},
{word:"UNIT",clue:"Single item",kr:"단위"},
{word:"UPON",clue:"On top of",kr:"~위에"},
{word:"USED",clue:"Previously owned",kr:"사용된"},
{word:"USER",clue:"Operator",kr:"사용자"},
{word:"VARY",clue:"Change",kr:"변하다"},
{word:"VASE",clue:"Flower container",kr:"꽃병"},
{word:"VAST",clue:"Huge",kr:"광대한"},
{word:"VEIN",clue:"Blood vessel",kr:"혈관"},
{word:"VENT",clue:"Air opening",kr:"환기구"},
{word:"VERB",clue:"Action word",kr:"동사"},
{word:"VERY",clue:"Extremely",kr:"매우"},
{word:"VEST",clue:"Sleeveless top",kr:"조끼"},
{word:"VIEW",clue:"Sight",kr:"전망"},
{word:"VINE",clue:"Climbing plant",kr:"덩굴"},
{word:"VISA",clue:"Travel document",kr:"비자"},
{word:"VOID",clue:"Empty space",kr:"공허"},
{word:"VOTE",clue:"Cast ballot",kr:"투표하다"},
{word:"WAGE",clue:"Pay",kr:"임금"},
{word:"WAIT",clue:"Stay put",kr:"기다리다"},
{word:"WAKE",clue:"Stop sleeping",kr:"일어나다"},
{word:"WANT",clue:"Desire",kr:"원하다"},
{word:"WARM",clue:"Slightly hot",kr:"따뜻한"},
{word:"WARN",clue:"Alert",kr:"경고하다"},
{word:"WASH",clue:"Clean",kr:"씻다"},
{word:"WEAK",clue:"Not strong",kr:"약한"},
{word:"WEAR",clue:"Put on",kr:"입다"},
{word:"WEED",clue:"Unwanted plant",kr:"잡초"},
{word:"WELL",clue:"Good",kr:"좋은"},
{word:"WEST",clue:"Sunset direction",kr:"서쪽"},
{word:"WHAT",clue:"Which thing",kr:"무엇"},
{word:"WHEN",clue:"At what time",kr:"언제"},
{word:"WIDE",clue:"Broad",kr:"넓은"},
{word:"WIFE",clue:"Married woman",kr:"아내"},
{word:"WILD",clue:"Untamed",kr:"야생의"},
{word:"WILL",clue:"Future tense",kr:"~할 것이다"},
{word:"WING",clue:"Bird part",kr:"날개"},
{word:"WINK",clue:"Eye signal",kr:"윙크"},
{word:"WIPE",clue:"Clean off",kr:"닦다"},
{word:"WIRE",clue:"Metal thread",kr:"철사"},
{word:"WISE",clue:"Smart",kr:"현명한"},
{word:"WISH",clue:"Desire",kr:"소원"},
{word:"WITH",clue:"Together",kr:"함께"},
{word:"WOMB",clue:"Baby place",kr:"자궁"},
{word:"WOOL",clue:"Sheep hair",kr:"양털"},
{word:"WORM",clue:"Ground crawler",kr:"지렁이"},
{word:"WORN",clue:"Used a lot",kr:"닳은"},
{word:"WRAP",clue:"Cover",kr:"싸다"},
{word:"YARD",clue:"Outdoor space",kr:"마당"},
{word:"YAWN",clue:"Tired mouth",kr:"하품"},
{word:"YEAH",clue:"Yes",kr:"그래"},
{word:"YELL",clue:"Shout",kr:"소리지르다"},
{word:"YOUR",clue:"Belonging to you",kr:"너의"},
{word:"ZERO",clue:"Nothing",kr:"영"},
{word:"ZONE",clue:"Area",kr:"구역"},
{word:"APPLE",clue:"Red or green fruit",kr:"빨간색 또는 녹색 과일"},
{word:"BEACH",clue:"Sandy shore",kr:"모래가 있는 해안"},
{word:"CHAIR",clue:"Sitting furniture",kr:"앉는 가구"},
{word:"DANCE",clue:"Rhythmic movement",kr:"리듬에 맞춘 움직임"},
{word:"EARTH",clue:"Our planet",kr:"우리 행성"},
{word:"HORSE",clue:"Riding animal",kr:"타는 동물"},
{word:"JUICE",clue:"Fruit drink",kr:"과일 음료"},
{word:"KNIFE",clue:"Cutting tool",kr:"자르는 도구"},
{word:"LEMON",clue:"Sour citrus",kr:"신맛 감귤류"},
{word:"MONEY",clue:"Currency",kr:"화폐"},
{word:"NIGHT",clue:"Dark hours",kr:"어두운 시간"},
{word:"OCEAN",clue:"Large body of salt water",kr:"큰 바닷물 수역"},
{word:"PAINT",clue:"Coloring substance",kr:"색칠하는 물질"},
{word:"QUEEN",clue:"Female monarch",kr:"여성 군주"},
{word:"RIVER",clue:"Flowing water body",kr:"흐르는 물줄기"},
{word:"STORM",clue:"Severe weather",kr:"심한 날씨"},
{word:"TABLE",clue:"Dining furniture",kr:"식사용 가구"},
{word:"WATER",clue:"H2O",kr:"H2O"},
{word:"WORLD",clue:"The Earth",kr:"지구 전체"},
{word:"BRAIN",clue:"Thinking organ",kr:"생각하는 기관"},
{word:"BREAD",clue:"Baked staple food",kr:"구운 주식"},
{word:"CANDY",clue:"Sweet treat",kr:"달콤한 간식"},
{word:"CHILD",clue:"Young person",kr:"어린 사람"},
{word:"CLOCK",clue:"Time device",kr:"시간 장치"},
{word:"CLOUD",clue:"Sky formation",kr:"하늘의 형성물"},
{word:"DREAM",clue:"Sleep vision",kr:"수면 중 환상"},
{word:"DRESS",clue:"Woman's garment",kr:"여성 의류"},
{word:"DRINK",clue:"Beverage",kr:"음료"},
{word:"FIELD",clue:"Open land",kr:"열린 땅"},
{word:"FLOOR",clue:"Walking surface",kr:"걷는 면"},
{word:"FRUIT",clue:"Plant produce",kr:"식물 생산물"},
{word:"GLASS",clue:"Transparent material",kr:"투명한 재료"},
{word:"GRASS",clue:"Lawn plant",kr:"잔디밭 식물"},
{word:"GREEN",clue:"Color of leaves",kr:"잎의 색깔"},
{word:"HEART",clue:"Pumping organ",kr:"펌프질하는 기관"},
{word:"HOTEL",clue:"Lodging place",kr:"숙박 장소"},
{word:"HOUSE",clue:"Living building",kr:"거주 건물"},
{word:"IMAGE",clue:"Visual representation",kr:"시각적 표현"},
{word:"LIGHT",clue:"Illumination",kr:"조명"},
{word:"LUNCH",clue:"Midday meal",kr:"한낮 식사"},
{word:"MAGIC",clue:"Supernatural power",kr:"초자연적 힘"},
{word:"MATCH",clue:"Fire starter",kr:"불 붙이는 막대"},
{word:"METAL",clue:"Shiny element",kr:"빛나는 원소"},
{word:"MOVIE",clue:"Motion picture",kr:"동영상 작품"},
{word:"MUSIC",clue:"Melodic sound",kr:"선율적 소리"},
{word:"NURSE",clue:"Medical caregiver",kr:"의료 간병인"},
{word:"PAPER",clue:"Writing material",kr:"글 쓰는 재료"},
{word:"PARTY",clue:"Celebration event",kr:"축하 행사"},
{word:"PEACE",clue:"Absence of war",kr:"전쟁의 부재"},
{word:"PHONE",clue:"Calling device",kr:"전화 장치"},
{word:"PHOTO",clue:"Captured image",kr:"포착된 이미지"},
{word:"PIANO",clue:"Keyboard instrument",kr:"건반 악기"},
{word:"PIZZA",clue:"Italian dish",kr:"이탈리아 요리"},
{word:"PLACE",clue:"Location",kr:"위치"},
{word:"PLANE",clue:"Flying vehicle",kr:"나는 탈것"},
{word:"PLANT",clue:"Growing organism",kr:"자라는 생물"},
{word:"PLATE",clue:"Dinner dish",kr:"식사용 접시"},
{word:"POWER",clue:"Strength or energy",kr:"힘 또는 에너지"},
{word:"PRICE",clue:"Cost",kr:"비용"},
{word:"PRIZE",clue:"Award",kr:"상"},
{word:"RADIO",clue:"Audio broadcast device",kr:"음성 방송 장치"},
{word:"SALAD",clue:"Vegetable dish",kr:"채소 요리"},
{word:"SCENE",clue:"View or setting",kr:"풍경 또는 배경"},
{word:"SHARK",clue:"Ocean predator",kr:"바다 포식자"},
{word:"SHEEP",clue:"Wool animal",kr:"털실 동물"},
{word:"SHELL",clue:"Beach treasure",kr:"해변의 보물"},
{word:"SHIRT",clue:"Upper body garment",kr:"상체 의류"},
{word:"SHOES",clue:"Footwear",kr:"발에 신는 것"},
{word:"SLEEP",clue:"Rest state",kr:"휴식 상태"},
{word:"SMILE",clue:"Happy expression",kr:"행복한 표현"},
{word:"SMOKE",clue:"Fire byproduct",kr:"불의 부산물"},
{word:"SNAKE",clue:"Slithering reptile",kr:"기어가는 파충류"},
{word:"SOUND",clue:"Audio",kr:"오디오"},
{word:"SPACE",clue:"Outer cosmos",kr:"외부 우주"},
{word:"SPOON",clue:"Eating utensil",kr:"먹는 도구"},
{word:"SPORT",clue:"Athletic activity",kr:"운동 활동"},
{word:"STAGE",clue:"Performance platform",kr:"공연 무대"},
{word:"STEAM",clue:"Hot water vapor",kr:"뜨거운 수증기"},
{word:"STEEL",clue:"Strong alloy",kr:"강한 합금"},
{word:"STONE",clue:"Rock",kr:"바위"},
{word:"STORE",clue:"Shop",kr:"가게"},
{word:"STORY",clue:"Narrative tale",kr:"서사적 이야기"},
{word:"STUDY",clue:"Learn",kr:"배우다"},
{word:"SUGAR",clue:"Sweet substance",kr:"달콤한 물질"},
{word:"TIGER",clue:"Striped big cat",kr:"줄무늬 큰 고양잇과"},
{word:"TOAST",clue:"Browned bread",kr:"갈색으로 구운 빵"},
{word:"TODAY",clue:"This day",kr:"이 날"},
{word:"TOWER",clue:"Tall structure",kr:"높은 구조물"},
{word:"TRAIN",clue:"Rail vehicle",kr:"철도 차량"},
{word:"TRUCK",clue:"Large vehicle",kr:"큰 차량"},
{word:"TRUTH",clue:"Fact",kr:"사실"},
{word:"VIDEO",clue:"Moving pictures",kr:"움직이는 그림"},
{word:"WATCH",clue:"Wrist timepiece",kr:"손목 시계"},
{word:"WHEEL",clue:"Round roller",kr:"둥근 롤러"},
{word:"WHITE",clue:"Snow color",kr:"눈의 색깔"},
{word:"WOMAN",clue:"Adult female",kr:"성인 여성"},
{word:"YOUTH",clue:"Young age",kr:"어린 나이"},
{word:"ZEBRA",clue:"Striped animal",kr:"줄무늬 동물"},
{word:"ANIMAL",clue:"Living creature",kr:"살아있는 생물"},
{word:"BANANA",clue:"Yellow fruit",kr:"노란 과일"},
{word:"CAMERA",clue:"Photo device",kr:"사진 장치"},
{word:"CASTLE",clue:"Royal fortress",kr:"왕족 요새"},
{word:"COFFEE",clue:"Morning beverage",kr:"아침 음료"},
{word:"DOCTOR",clue:"Medical professional",kr:"의료 전문가"},
{word:"DRAGON",clue:"Mythical beast",kr:"신화 속 짐승"},
{word:"FAMILY",clue:"Related group",kr:"관계된 집단"},
{word:"FLOWER",clue:"Plant bloom",kr:"식물의 꽃"},
{word:"FOREST",clue:"Tree-filled area",kr:"나무로 가득한 지역"},
{word:"FRIEND",clue:"Close companion",kr:"가까운 동반자"},
{word:"GARDEN",clue:"Plant growing area",kr:"식물 재배 구역"},
{word:"GUITAR",clue:"String instrument",kr:"현악기"},
{word:"ISLAND",clue:"Water-surrounded land",kr:"물에 둘러싸인 땅"},
{word:"JUNGLE",clue:"Tropical forest",kr:"열대 우림"},
{word:"KITTEN",clue:"Baby cat",kr:"아기 고양이"},
{word:"LETTER",clue:"Written message",kr:"쓴 메시지"},
{word:"MARKET",clue:"Shopping place",kr:"쇼핑 장소"},
{word:"MONKEY",clue:"Primate",kr:"영장류"},
{word:"MOTHER",clue:"Female parent",kr:"여성 부모"},
{word:"MUSEUM",clue:"Art building",kr:"예술 건물"},
{word:"NATURE",clue:"Natural world",kr:"자연 세계"},
{word:"ORANGE",clue:"Citrus fruit",kr:"감귤류 과일"},
{word:"RABBIT",clue:"Hopping animal",kr:"뛰어다니는 동물"},
{word:"SCHOOL",clue:"Learning place",kr:"배우는 장소"},
{word:"SUMMER",clue:"Hot season",kr:"더운 계절"},
{word:"WINDOW",clue:"Wall opening",kr:"벽의 개구부"},
{word:"WINTER",clue:"Cold season",kr:"추운 계절"},
{word:"AIRPORT",clue:"Plane terminal",kr:"비행기 터미널"},
{word:"BROTHER",clue:"Male sibling",kr:"남성 형제자매"},
{word:"CAPTAIN",clue:"Ship leader",kr:"배의 지도자"},
{word:"CHICKEN",clue:"Farm bird",kr:"농장 조류"},
{word:"COUNTRY",clue:"Nation",kr:"국가"},
{word:"DIAMOND",clue:"Precious gem",kr:"귀중한 보석"},
{word:"DOLPHIN",clue:"Smart sea mammal",kr:"똑똑한 바다 포유류"},
{word:"EVENING",clue:"Late afternoon",kr:"늦은 오후"},
{word:"FACTORY",clue:"Manufacturing place",kr:"제조 장소"},
{word:"FREEDOM",clue:"Liberty",kr:"자유로움"},
{word:"HISTORY",clue:"Past events",kr:"과거 사건들"},
{word:"KITCHEN",clue:"Cooking room",kr:"요리하는 방"},
{word:"LIBRARY",clue:"Book building",kr:"책 건물"},
{word:"MACHINE",clue:"Mechanical device",kr:"기계 장치"},
{word:"MORNING",clue:"Early day",kr:"이른 낮"},
{word:"MYSTERY",clue:"Unsolved puzzle",kr:"풀리지 않은 퍼즐"},
{word:"PICTURE",clue:"Image",kr:"이미지"},
{word:"RAINBOW",clue:"Colorful arc",kr:"다채로운 호"},
{word:"SCIENCE",clue:"Knowledge field",kr:"지식 분야"},
{word:"STUDENT",clue:"Learner",kr:"배우는 사람"},
{word:"TEACHER",clue:"Educator",kr:"교육자"},
{word:"WEATHER",clue:"Climate conditions",kr:"기후 상태"},
{word:"WEEKEND",clue:"Saturday and Sunday",kr:"토요일과 일요일"}
];
